name: ArtiWave Continuous Deploiement

on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Joke
        run: echo joke
