name: ArtiWave Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    if: ${{!contains(github.event.head_commit.message, '#code')}}
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: nimda

      mongo-express:
        image: mongo-express
        ports:
          - 8081:8081
        env:
          ME_CONFIG_MONGODB_ADMINUSERNAME: admin
          ME_CONFIG_MONGODB_ADMINPASSWORD: nimda
          ME_CONFIG_MONGODB_URL: mongodb://admin:nimda@mongo:27017/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  okdeploy:
    needs: [tests]
    if: ${{github.event_name== 'push' && github.ref_name == 'main'}}
    uses: ./.github/workflows/cd.yml